# Generated by Django 4.2.1 on 2023-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmyid', '0003_alter_profile_user_id_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='language_code'),
        ),
    ]
