# Generated by Django 4.2.1 on 2023-05-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getmyid', '0005_alter_profile_lastname_alter_profile_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Userlist_getmyid', 'verbose_name_plural': 'Userlist_getmyid'},
        ),
    ]
