# Generated by Django 4.2.1 on 2023-05-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('api_id', models.CharField(blank=True, max_length=200, null=True)),
                ('api_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
