# Generated by Django 4.2.1 on 2023-05-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots_config', '0002_telegramapi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramapi',
            options={'verbose_name': 'Telegram Api', 'verbose_name_plural': 'Telegram Apis'},
        ),
        migrations.AlterModelTable(
            name='telegramapi',
            table='telegram_api',
        ),
    ]
