# Generated by Django 4.2.1 on 2023-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots_config', '0004_remove_admin_bots_bot_admin_bots_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_bots',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('partner', 'partner'), ('block', 'block')], default='partner', max_length=50, null=True),
        ),
    ]
