# Generated by Django 4.2.1 on 2023-05-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='user id')),
                ('username', models.CharField(blank=True, null=True, verbose_name='username')),
                ('fistname', models.CharField(blank=True, null=True, verbose_name='First_name')),
                ('lastname', models.CharField(blank=True, null=True, verbose_name='Lastname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Bot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Userlist',
                'verbose_name_plural': 'Userlist',
                'db_table': 'common_profile',
            },
        ),
    ]
