# Generated by Django 4.2.1 on 2023-05-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_profile_fistname_alter_profile_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fistname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
    ]
