# Generated by Django 4.2.1 on 2023-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_profile_fistname_remove_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fistname',
            field=models.TextField(blank=True, null=True, verbose_name='First_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='language_code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(blank=True, null=True, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.BigIntegerField(default=0, verbose_name='user id'),
            preserve_default=False,
        ),
    ]
